[patch.crates-io]
serial = { git = "https://github.com/bytebeamio/serial-rs", branch = "android_fix" }

[workspace]
members = [
    "tunshell-shared",
    "tunshell-client",
    "tunshell-server",
    "tunshell-tests",
]