[package]
name = "tunshell-tests"
version = "0.1.0"
authors = ["Elliot Levin <elliotlevin@hotmail.com>"]
edition = "2018"
autotests = false

[dependencies]
tunshell-client = { path = "../tunshell-client" }
tunshell-server = { path = "../tunshell-server" }
tokio = { workspace = true, features = ["rt-multi-thread"] }
reqwest = { version = "0.10", features = ["json"] }
env_logger = { workspace = true }
futures = { workspace = true }
log = { workspace = true }

[[test]]
name = "tests"
path = "tests/lib.rs"
